#!/usr/bin/env bash
# DECOY-PATCH CONTROL + the unconditioned arm's sequences. One pod session.
#
# This is the control that can FALSIFY the conditioning result. Everything run so far
# compares the conditioned arm against a resampled null on the same structures, so none of
# it can separate "the hotspots steered RFdiffusion" from "RFdiffusion docks antibodies on
# that face of PD-1 anyway". Nothing has ever asked it for a different face. This does.
#
# The decoy patch is ALREADY SELECTED AND VERIFIED on CPU -- see results/decoy_patch.md:
# 26 residues, RMS spread 10.15 A against the epitope's 9.85 A, ZERO overlap, 165.9 deg
# around the centroid, and the 18 existing conditioned backbones score 0.000 on it against
# 0.712 on the real epitope. So the two faces already separate in practice, which is what
# makes this run interpretable.
#
# BLOCK A needs RFdiffusion ONLY. Targeting is measured on BACKBONES (scripts/70, 94, 95
# all parse bb/*.pdb), so no ProteinMPNN and no RF2 for the decoy arm. Measured cost from
# the 2026-09-21 run: 161 s/backbone mean (median 148, max 288), so 18 backbones is
# ~0.81 GPU-hours, NOT the 2-4 h STATE.md used to estimate.
#
# BLOCK B is the only reason the unconditioned arm needs a GPU at all: ProteinMPNN. The
# backbones already exist locally and their targeting baseline is already computed
# (0.500 vs the conditioned 0.712 -- scripts/96). Folding and scoring the sequences runs
# LOCALLY on Blackwell for free. Measured: 41 s for 30 designs.
set -uo pipefail

RFAB="${RFAB:-$HOME/RFantibody}"
WORK="${WORK:-/workspace/c2_decoy}"    # /workspace = VOLUME disk, survives a pod stop.
                                       # Container disk is erased on stop -- never write here.
K=18; RECYCLES=10

# Decoy hotspots, generated by scripts/95_decoy_patch_control.py. Upload
# pod/inputs_decoy_hotspots.txt to $RFAB/inputs/ alongside the originals.
HOT=$(cat "$RFAB/inputs/decoy_hotspots.txt")
LOOPS="H1:7,H2:6,H3:5-13,L1:8-13,L2:7,L3:9-11"
# 0-BASED ORDINALS within chain T, NOT author numbering. RFdiffusion renumbers its output
# continuously across chains, so a check keyed on the wrong form returns a clean,
# believable ZERO -- this project lost a day to exactly that.
ORD_DECOY="3,5,6,7,8,9,10,12,18,20,22,24,64,65,66,67,68,69,70,71,72,73,74,76,78,110"

mkdir -p "$WORK"/{bb,seq_uncond,logs}
HB="$WORK/heartbeat.log"
log() { echo "[$(date -u +%H:%M:%S)] $*" | tee -a "$HB"; }

log "=== BLOCK A: $K DECOY-conditioned backbones, $RECYCLES recycles ==="
log "target=$RFAB/inputs/pd1_T.pdb  decoy hotspots=26  work=$WORK"

for i in $(seq 1 $K); do
  OUT="$WORK/bb/dec_${i}"
  # Resume keys on the ARTEFACT, never on a process pattern: `pgrep -f` matched a stale
  # shell's argv five times in this project, costing 2h39m and 1h22m of idle hardware.
  if [ -f "${OUT}_0.pdb" ]; then log "dec_$i: already on disk, skipping"; continue; fi
  S=$(date +%s)
  cd "$RFAB"
  uv run python scripts/rfdiffusion_inference.py --config-name antibody \
      antibody.target_pdb="$RFAB/inputs/pd1_T.pdb" \
      antibody.framework_pdb="$RFAB/inputs/framework.pdb" \
      inference.ckpt_override_path="$RFAB/weights/RFdiffusion_Ab.pt" \
      "ppi.hotspot_res=[$HOT]" "antibody.design_loops=[$LOOPS]" \
      inference.num_designs=1 inference.output_prefix="$OUT" \
      inference.seed=$((2000 + i)) > "$WORK/logs/dec_$i.log" 2>&1
  D=$(( $(date +%s) - S ))
  # Exit code is NOT evidence. RFdiffusion's failure modes here are silent truncation and
  # NaN output; assert the artefact exists.
  if [ ! -f "${OUT}_0.pdb" ]; then log "dec_$i: FAILED after ${D}s, no artefact"; continue; fi
  # `26/26 hotspots resolved` proves the tool RECEIVED the conditioning, not that it
  # changed the output -- unmatched hotspots are SILENTLY ignored, so assert the count.
  HS=$(grep -c "as a hotspot" "$WORK/logs/dec_$i.log" || echo 0)
  [ "$HS" -eq 26 ] || log "dec_$i: WARNING only $HS/26 DECOY hotspots resolved"
  echo "$(python3 "${CHECK:-/workspace/lock/check_backbone.py}" "${OUT}_0.pdb" "$ORD_DECOY" 2>/dev/null || echo '{}')" \
      | sed "s/^{/{\"backbone\":\"dec_$i\",\"sec\":$D,/" >> "$WORK/decoy_backbones.jsonl"
  log "dec_$i: ${D}s, decoy hotspots_resolved=$HS"
done
log "BLOCK A done: $(ls "$WORK"/bb/*_0.pdb 2>/dev/null | wc -l)/$K backbones"

# ---------------------------------------------------------------------------
# BLOCK B: sequences for the UNCONDITIONED backbones. Upload the 18 from
# runs/challenge2_pod/c2/unconditioned/ to $WORK/uncond_bb/ first.
# ---------------------------------------------------------------------------
if [ -d "$WORK/uncond_bb" ]; then
  log "=== BLOCK B: ProteinMPNN on the unconditioned backbones ==="
  S=$(date +%s)
  cd "$RFAB"
  uv run proteinmpnn -i "$WORK/uncond_bb" -o "$WORK/seq_uncond" -n 3 -t 0.2 \
      > "$WORK/logs/mpnn_uncond.log" 2>&1
  log "mpnn: $(( $(date +%s) - S ))s, $(ls "$WORK/seq_uncond"/*.pdb 2>/dev/null | wc -l) designs"
else
  log "BLOCK B skipped: $WORK/uncond_bb not present (upload the 18 unconditioned backbones)"
fi

log "=== DONE. Retrieve $WORK/bb, $WORK/seq_uncond, $WORK/*.jsonl, $WORK/logs ==="
log "Then, locally:  uv run python scripts/95_decoy_patch_control.py --analyse <bb dir>"
