"""Shared submission prose.

Challenge 2's `reproducing_our_numbers.md` lives here rather than inside a packaging
script because it was generated by `scripts/75` and then ORPHANED: `scripts/105` swapped
in the bb_8_0 design, rewrote scores.md and methods_and_limitations.md, and left this file
untouched. It shipped describing the previous design -- ipSAE 0.781 against the 0.904 the
packaged structure actually scores. A template that only one of two generators can reach
is a bug waiting for the second generator; keeping it here means every packager calls the
same function with its own numbers.

`scripts/58_validate_submission.py::check_docs_against_scores` is the guard that catches a
recurrence, by cross-checking every value a packaged doc asserts against a recomputation
from the package itself.
"""
from __future__ import annotations

from locksmith.metrics import germline


def challenge2_repro_md(win: dict, conv: dict, team: str, heavy: str) -> str:
    """Challenge 2's reproducing_our_numbers.md, for whichever design is being shipped.

    `win` is the raw metric dict of the design actually written into the package -- the
    model_0 values, not the median across diffusion samples, because the package ships
    model_0 and a reviewer recomputing from those files will get model_0's numbers.
    """
    TEAM = team  # the template was lifted verbatim from scripts/75, which used this name

    # The alternative-convention number MUST be recomputed for the design being shipped.
    # The version of this template inherited from scripts/75 hardcoded "40.0% against all
    # 6,864 IGHV x IGHD x IGHJ recombinations" beside a parameterised `cdrh3_identity`.
    # Neither figure is reproducible from this repo: the germline DB holds 249 V, 76 D and
    # 14 J (264,936 combinations, not 6,864), and no code here enumerates recombinations.
    # The claim was cut rather than re-derived. `best_segment` is the alternative reading
    # this project actually implements, so it is the one quoted -- and it is computed, so
    # it cannot be left behind by a design swap the way 40.0 was.
    _alt = germline.compute(heavy, convention="best_segment").value
    return f"""# Reproducing every number we report — Challenge 2

Written because a reviewer should be able to re-derive our numbers from what we handed
over, and because Challenge 1 ships this file and Challenge 2 did not.

## Seven metrics, not eight

§5.2 applies DockQ to Challenge 1 only — a de novo design has no reference structure. So
`DockQ` is absent here, and with it **the only metric in the rubric that compares the
prediction to anything external.** Every number below is computed from the two files in
`structures/`, which we generated. A confidently wrong pose scores exactly like a right one.

| metric | source | our value |
|---|---|---|
| `ipsae` | `vendor/ipsae/ipsae.py` on the PAE JSON + PDB, cutoffs {conv['ipsae_pae_cutoff']}/{conv['ipsae_dist_cutoff']} | {win['ipsae']:.3f} |
| `dg`, `contacts` | PRODIGY, chain selection `A,B` vs `C` | {win['dg']:.1f}, {win['contacts']:.0f} |
| `iface_plddt` | mean B-factor over interface residues, {conv['interface_dist_cutoff']} Å heavy-atom | {win['iface_plddt']:.2f} |
| `cdr_sasa` | freesasa over the six CDRs, `{conv['cdr_sasa_state']}` state | {win['cdr_sasa']:.1f} |
| `netsolp` | NetSolP **ESM1b** (the tool's own default), Fv, `{conv['netsolp_chain_agg']}` over chains | {win['netsolp']:.3f} |
| `cdrh3_identity` | **human germline**, not Keytruda — see below | {win['cdrh3_identity']:.1f}% |

## The one that needs explaining: novelty against germline

§6.3.1 scores Challenge 2 novelty as CDR-H3 identity *"compared to human germline CDR
sequences"*, and does not say how. **CDR-H3 has no single germline template**: it spans the
V(D)J junction, and the N-region insertions have no germline counterpart at all. So the
metric is a best-match search, not a string comparison, and the convention has to be
declared.

Ours (`src/locksmith/metrics/germline.py`): best **exact V prefix** + best **D substring,
3 forward reading frames** + best **exact J suffix**, non-overlapping, scored as
`covered / len(query)`. V is a prefix and J a suffix because exonuclease trimming removes
segment *ends*; D is a substring because it is trimmed at both ends and read in any frame.

**The convention moves the number.** Scoring the same CDR-H3 as best global-alignment
identity against any single germline segment (`best_segment`) gives **{_alt:.1f}%**, where
the V(D)J-coverage reading we report as `cdrh3_identity` gives **{win['cdrh3_identity']:.1f}%**.
Both readings are defensible against §6.3.1's wording and **both are far inside the Good
band (<70%) and the <95% cutoff**, so nothing about the score turns on it. We record the
disagreement rather than hide it.

Validated on cases whose answers are derivable: a verbatim germline junction scores
**100.0%**, and **242 of 249** IGHV alleles return themselves (the 7 others are exact ties).

## Verifying the package end to end

```
uv run python scripts/58_validate_submission.py submission/{TEAM}
```

Reads **only** this folder — no run directory, no cached score — and re-derives all seven
metrics. Exits non-zero on any structural problem or failed cutoff.

## Provenance

Backbones came from RFdiffusion/RFantibody on a rented RTX 3090 and were retrieved to local
disk; **all 258 artefact files are sha256-verified against the server**. The structure here
was folded locally with Boltz-2 at `recycling_steps=10`, seed 1, `diffusion_samples` 5 with
`model_0` submitted. **Both of those settings move the score** — see
`methods_and_limitations.md`, which gives the measured envelopes rather than a single
number.
"""
