#!/usr/bin/env python3
"""Gates 1c and 1d, and the question underneath both: does ipSAE track anything real?

Outputs results/panel_g1c_g1d.md.

STATISTICS, AND WHY EACH GUARD IS HERE
--------------------------------------
1. RESTRICTED RANGE. The Fv screen's job is separating designs that already
   passed earlier filters, so its operating regime is the narrow high-quality
   band. Spearman over a panel spanning pembrolizumab to poly-Gly measures a task
   that never occurs and will look flattering. Both are reported; the restricted
   one leads.

2. ATTENUATION. Boltz-2 is a diffusion model, so each ipSAE value is a noisy
   draw. A correlation between two noisy measurements is attenuated:
       rho_obs ~= rho_true * sqrt(r_fv * r_fab)
   With r ~ 0.75 each, a true 0.80 presents as 0.60 -- exactly the gate
   threshold. So the noise floor is measured first and the corrected value is
   reported SEPARATELY and labelled, never as if it were observed.

3. SAMPLING ERROR. n=14 gives SE(z) = 1/sqrt(n-3) = 0.30, so a point estimate of
   0.60 carries a 95% CI of roughly [0.10, 0.86]. A bare point estimate against a
   0.6 threshold would be false precision. CIs are reported throughout.
"""
from __future__ import annotations

import json
import math
import sys
from collections import defaultdict
from pathlib import Path

import numpy as np
from scipy import stats

from locksmith.config import load as load_cfg
from locksmith.design.variants import load as load_variants

SCORES = Path("runs/panel/scores.jsonl")
OUT = Path("results/panel_g1c_g1d.md")


def rows():
    return [json.loads(l) for l in SCORES.read_text().splitlines() if l.strip()]


def spearman_ci(x, y, alpha=0.05):
    """Spearman rho with a Fisher-z confidence interval."""
    x, y = np.asarray(x, float), np.asarray(y, float)
    n = len(x)
    if n < 4:
        return (float("nan"), float("nan"), float("nan"), float("nan"), n)
    rho, p = stats.spearmanr(x, y)
    if not np.isfinite(rho) or abs(rho) >= 1.0:
        return (rho, p, float("nan"), float("nan"), n)
    z = np.arctanh(rho)
    se = 1.0 / math.sqrt(n - 3)
    lo, hi = np.tanh(z - 1.96 * se), np.tanh(z + 1.96 * se)
    return (rho, p, lo, hi, n)


def fmt_ci(t):
    rho, p, lo, hi, n = t
    if not np.isfinite(rho):
        return f"n={n}, too few points"
    ci = f"[{lo:+.2f}, {hi:+.2f}]" if np.isfinite(lo) else "[--]"
    return f"rho = {rho:+.3f}  95% CI {ci}  p = {p:.3f}  n = {n}"


def main() -> int:
    if not SCORES.exists():
        print("no scores yet", file=sys.stderr)
        return 1
    cfg = load_cfg()
    cutoff = cfg.bands()["ipsae"].cutoff
    variants = {v.name: v for v in load_variants(Path("designs/variants.json"))}
    R = rows()

    # AF2 in single-sequence mode did not produce physically valid structures
    # (pLDDT 37, ipTM 0.11, inter-chain contacts at 0.5-0.9 A = interpenetrating
    # atoms). Excluded from every regression as a PREDICTOR failure. Note this is
    # not a value threshold: the poly-Gly variants also score near zero and those
    # are legitimate results for a design that genuinely does not bind.
    AF2_SS = "alphafold2_multimer_v3"
    af2_ss_failed = [r for r in R if r["predictor"] == AF2_SS]
    R = [r for r in R if r["predictor"] != AF2_SS]

    L = []
    def w(s=""):
        L.append(s)

    w("# Gates 1c and 1d — does ipSAE track structural correctness?")
    w()
    w(f"Panel of {len(variants)} pembrolizumab variants, generated by substituting "
      f"IMGT CDR positions (fixed seed). Scored with the vendored `ipsae.py` at the "
      f"pinned 10/15 cutoffs and DockQ against the 5GGS crystal.")
    w()

    # ---------------------------------------------------------------- noise floor
    w("## 1. The noise floor — measured first, because it bounds everything else")
    w()
    noise = defaultdict(list)
    for r in R:
        if r["predictor"] == "boltz2" and r.get("ipsae") is not None:
            noise[(r["variant"], r["construct"])].append(r["ipsae"])
    multi = {k: v for k, v in noise.items() if len(v) >= 3}

    reliability = {}
    if multi:
        w("Within-variant ipSAE across seeds (Boltz-2 is a diffusion model: different "
          "seeds give genuinely different structures, not just different confidence).")
        w()
        w("| variant | construct | n seeds | mean | sd | spread |")
        w("|---|---|---|---|---|---|")
        within = defaultdict(list)
        for (var, form), vals in sorted(multi.items()):
            a = np.array(vals)
            w(f"| {var} | {form} | {len(a)} | {a.mean():.3f} | {a.std(ddof=1):.3f} | "
              f"{a.max()-a.min():.3f} |")
            within[form].append(a.var(ddof=1))
        w()
        for form in ("fv", "fab"):
            if form not in within:
                continue
            s2_within = float(np.mean(within[form]))
            panel_vals = [r["ipsae"] for r in R
                          if r["predictor"] == "boltz2" and r["construct"] == form
                          and r["seed"] == 1 and r.get("ipsae") is not None]
            s2_obs = float(np.var(panel_vals, ddof=1)) if len(panel_vals) > 2 else float("nan")
            rel = max(0.0, 1.0 - s2_within / s2_obs) if s2_obs and np.isfinite(s2_obs) else float("nan")
            reliability[form] = rel
            w(f"- **{form}**: pooled within-variant variance {s2_within:.5f}; "
              f"across-panel variance {s2_obs:.5f}; "
              f"**reliability r = {rel:.3f}**")
        w()
        w("Reliability here is `1 - sigma2_within / sigma2_observed` — an intraclass "
          "correlation. It is estimated from only 3 variants, chosen to span the range, "
          "so it assumes seed noise is roughly constant across the quality range. A "
          "poly-Gly design plausibly has larger seed variance than pembrolizumab, which "
          "would make this an optimistic average.")
    else:
        w("*(noise run not yet complete)*")
    w()

    # ------------------------------------------------- reliability -> cost
    w("### 1.1 The reliability asymmetry, and what it costs")
    w()
    if reliability.get("fv") and reliability.get("fab"):
        rfv, rfab = reliability["fv"], reliability["fab"]
        secs = defaultdict(list)
        for r in R:
            if r["predictor"] == "boltz2" and r.get("seconds"):
                secs[r["construct"]].append(r["seconds"])
        tfv = float(np.mean(secs["fv"])) if secs["fv"] else float("nan")
        tfab = float(np.mean(secs["fab"])) if secs["fab"] else float("nan")
        w(f"**Fv ipSAE is a far noisier measurement than Fab ipSAE: r = {rfv:.2f} vs "
          f"{rfab:.2f}.** This is the under-constrained VH/VL elbow showing up as "
          "measurement error. A bare Fv has nothing to clamp the relative orientation of "
          "the two variable domains, so a diffusion model samples genuinely different "
          "elbow angles between seeds; the constant domains in a Fab pin it. The project "
          "predicted this qualitatively when it chose Fv-screen/Fab-confirm. Measured, it "
          "undermines the screen rather than supporting it.")
        w()
        w("Averaging over seeds would recover reliability (Spearman-Brown, "
          "`r_k = k*r / (1 + (k-1)*r)`) -- but it has to be paid for:")
        w()
        w("| Fv seeds | Fv reliability | Fv wall clock | vs one Fab fold |")
        w("|---|---|---|---|")
        for k in (1, 2, 3, 4):
            rk = k * rfv / (1 + (k - 1) * rfv)
            w(f"| {k} | {rk:.3f} | {k*tfv:.0f} s | {k*tfv/tfab:.2f}x |")
        w()
        k_needed = next((k for k in range(1, 9)
                         if k * rfv / (1 + (k - 1) * rfv) >= rfab), None)
        w(f"- One Fab fold measured at **{tfab:.0f} s**, one Fv fold at **{tfv:.0f} s** "
          f"(mean over the panel; both include ~100 s of fixed per-invocation overhead).")
        if k_needed:
            w(f"- Matching the Fab's reliability needs **{k_needed} Fv seeds** = "
              f"{k_needed*tfv:.0f} s, i.e. **{k_needed*tfv/tfab:.1f}x the cost of simply "
              f"folding the Fab**.")
        else:
            w(f"- **No number of Fv seeds reaches the Fab's reliability** "
              f"(r_inf = 1.0 asymptotically, but {rfab:.2f} needs "
              f"k > 8 and {8*tfv/tfab:.1f}x the Fab cost already).")
        w()
        w("**So the cheap screen is not cheap.** Even at 2 seeds the Fv costs more wall "
          "clock than the Fab it was supposed to save, and is still less reliable. The "
          "2.5x residue-count saving does not survive contact with the fixed per-fold "
          "overhead and the elbow noise.")
    w()

    # ---------------------------------------------------------------- G1c
    w("## 2. Gate 1c — does Fv ipSAE ranking predict Fab ipSAE ranking?")
    w()
    seed1 = [r for r in R if r["predictor"] == "boltz2" and r["seed"] == 1]
    fv = {r["variant"]: r for r in seed1 if r["construct"] == "fv"}
    fab = {r["variant"]: r for r in seed1 if r["construct"] == "fab"}
    paired = [(n, fv[n], fab[n]) for n in sorted(set(fv) & set(fab))
              if fv[n].get("ipsae") is not None and fab[n].get("ipsae") is not None]

    w("| variant | subs | CDR-H3 %id | Fv ipSAE | Fab ipSAE | Fv DockQ | Fab DockQ |")
    w("|---|---|---|---|---|---|---|")
    for n, a, b in paired:
        v = variants[n]
        w(f"| {n} | {v.n_subs} | {v.cdrh3_identity:.1f} | {a['ipsae']:.3f} | "
          f"{b['ipsae']:.3f} | {_f(a.get('dockq'))} | {_f(b.get('dockq'))} |")
    w()

    full = spearman_ci([a["ipsae"] for _, a, _ in paired],
                       [b["ipsae"] for _, _, b in paired])
    restricted = [(n, a, b) for n, a, b in paired
                  if a["ipsae"] >= cutoff and b["ipsae"] >= cutoff]
    restr = spearman_ci([a["ipsae"] for _, a, _ in restricted],
                        [b["ipsae"] for _, _, b in restricted])

    w(f"**Restricted range — the number the protocol actually rests on** "
      f"(both forms clearing the ipSAE cutoff of {cutoff}, i.e. the designs that "
      f"would survive to a Fab confirmation):")
    w()
    w(f"> {fmt_ci(restr)}")
    w()
    w(f"Full panel (includes destructive anchors; ranking a dead design below a live "
      f"one is trivial and this number describes a task that never occurs):")
    w()
    w(f"> {fmt_ci(full)}")
    w()
    rel_fv, rel_fab = reliability.get("fv"), reliability.get("fab")
    if rel_fv and rel_fab and rel_fv > 0 and rel_fab > 0:
        denom = math.sqrt(rel_fv * rel_fab)
        for nm, t in (("restricted", restr), ("full panel", full)):
            if np.isfinite(t[0]):
                w(f"- Attenuation-**corrected** {nm} rho = {t[0]/denom:+.3f} "
                  f"(= observed {t[0]:+.3f} / sqrt({rel_fv:.2f} x {rel_fab:.2f})). "
                  f"This is a *corrected* figure, not an observation.")
        w()

    # ---------------------------------------------------------------- ipSAE vs DockQ
    w("## 3. The substantive question — does ipSAE track structural correctness?")
    w()
    w("DockQ against the 5GGS crystal. For `v00_wt` this is genuine accuracy: same "
      "molecule, known answer. For the mutants it is **retention of the native binding "
      "mode**, which conflates prediction error with real structural change caused by "
      "the mutation. That is the right quantity for Challenge 1 but it is not "
      "ground-truth accuracy, and the regression below should be read accordingly.")
    w()
    w("| predictor | construct | slope (ipSAE per DockQ) | R2 | Spearman | n |")
    w("|---|---|---|---|---|---|")
    fits = {}
    for pred in sorted({r["predictor"] for r in R}):
        for form in ("fv", "fab"):
            pts = [(r["dockq"], r["ipsae"]) for r in R
                   if r["predictor"] == pred and r["construct"] == form
                   and r["seed"] == 1 and r.get("dockq") is not None
                   and r.get("ipsae") is not None]
            if len(pts) < 4:
                continue
            d = np.array([p[0] for p in pts]); i = np.array([p[1] for p in pts])
            lr = stats.linregress(d, i)
            rho = stats.spearmanr(d, i)
            fits[(pred, form)] = (lr, d, i)
            w(f"| {pred} | {form} | {lr.slope:+.3f} | {lr.rvalue**2:.3f} | "
              f"{rho.statistic:+.3f} | {len(pts)} |")
    w()

    # without destructive anchors (high leverage)
    w("Excluding the two poly-Gly anchors, which have high leverage:")
    w()
    w("| predictor | construct | slope | R2 | n |")
    w("|---|---|---|---|---|")
    for pred in sorted({r["predictor"] for r in R}):
        for form in ("fv", "fab"):
            pts = [(r["dockq"], r["ipsae"]) for r in R
                   if r["predictor"] == pred and r["construct"] == form
                   and r["seed"] == 1 and r.get("dockq") is not None
                   and r.get("ipsae") is not None
                   and variants[r["variant"]].kind != "destructive"]
            if len(pts) < 4:
                continue
            d = np.array([p[0] for p in pts]); i = np.array([p[1] for p in pts])
            lr = stats.linregress(d, i)
            w(f"| {pred} | {form} | {lr.slope:+.3f} | {lr.rvalue**2:.3f} | {len(pts)} |")
    w()

    # ---------------------------------------------------------------- G1d
    w("## 4. Gate 1d — is the Boltz/AF2 ipSAE gap a scale offset or deserved?")
    w()
    w("### 4.1 AlphaFold2 could not be run on the designs at all")
    w()
    w(f"All {len(af2_ss_failed)} ColabFold folds used `--msa-mode single_sequence`, "
      "because the default mode uploads the query to the **public MMseqs2 server** and "
      "a designed sequence must never go there. Every one of them failed to build a "
      "complex:")
    w()
    w("| | AF2 single-sequence | AF2 with MSAs (same complex) |")
    w("|---|---|---|")
    w("| pLDDT | 37.1 | 94.4 |")
    w("| pTM / ipTM | 0.231 / 0.111 | 0.917 / 0.891 |")
    w("| ipSAE | 0.000 | 0.654 |")
    w("| DockQ | 0.017 | 0.690 |")
    w("| min inter-chain distance | **0.5-0.9 A** (atoms interpenetrating) | normal |")
    w()
    w("This is a real property of AlphaFold2, not a pipeline fault: AF2 derives its "
      "structural signal from co-evolution in the MSA, and without one it does not fold "
      "complexes. Boltz-2 is far more robust single-sequence, which is exactly why the "
      "antibody chains can be given `empty` alignments in the first place.")
    w()
    w("**Consequence: G1d cannot be discharged on designed sequences under the current "
      "constraints.** AF2 needs MSAs; MSAs need either the public server (forbidden for "
      "designs) or a local sequence database (not installed). This is a cost decision, "
      "not something to engineer around -- see the session doc for the three options.")
    w()
    w("### 4.2 What can still be said, using the panel as a calibration curve")
    w()
    w("The one legitimate AF2-with-MSA point is pembrolizumab itself, whose sequence is "
      "published, so the server was a fair use. The panel now supplies something the "
      "previous single-point comparison lacked: a **Boltz ipSAE-vs-DockQ curve**. So ask "
      "the question properly -- *given a structure of DockQ 0.690, what ipSAE would Boltz "
      "have reported?* If AF2's 0.654 matches that prediction, the gap was fully explained "
      "by structure quality and there is no scale offset. If AF2 sits below it, the "
      "residual is the offset.")
    w()
    fb = fits.get(("boltz2", "fv"))
    af2msa = [r for r in R if r["predictor"].endswith("_msa") and r["construct"] == "fv"]
    if fb and af2msa:
        lr, d, i = fb
        a = af2msa[0]
        pred_at = lr.intercept + lr.slope * a["dockq"]
        resid = a["ipsae"] - pred_at
        sd_resid = float(np.std(i - (lr.intercept + lr.slope * d), ddof=2))
        w(f"- Boltz-2 Fv calibration curve: `ipSAE = {lr.intercept:+.3f} "
          f"{lr.slope:+.3f} x DockQ` (n={len(d)}, R2={lr.rvalue**2:.3f}, "
          f"residual sd {sd_resid:.3f})")
        w(f"- At AF2's DockQ of **{a['dockq']:.3f}**, Boltz's curve predicts ipSAE "
          f"**{pred_at:.3f}**")
        w(f"- AF2 actually reported **{a['ipsae']:.3f}** -> residual "
          f"**{resid:+.3f}** = **{abs(resid)/sd_resid:.1f} residual sd**")
        w()
        if abs(resid) < 2 * sd_resid:
            w(f"So the AF2 point sits **within {abs(resid)/sd_resid:.1f} sd of the Boltz "
              f"curve**. On this evidence the 0.841-vs-0.654 gap reported on 2026-09-16 "
              f"is **largely explained by structure quality, not by a PAE scale offset** "
              f"-- AF2 was less confident because it was less right. The control that "
              f"complicated the single-point comparison now resolves it in that direction.")
        else:
            w(f"So the AF2 point sits **{abs(resid)/sd_resid:.1f} residual sd from the "
              f"Boltz curve**, which is a genuine offset beyond what structure quality "
              f"explains.")
        w()
        w("**Weight this appropriately: n=1 for AF2.** One point cannot establish an "
          "offset, only fail to find one. What has improved is the reference -- the "
          "comparison is now against a 14-point calibration curve with a measured "
          "residual spread, instead of against a single other number.")
    w()

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(L) + "\n")
    print("\n".join(L))
    print(f"\n-> {OUT}")
    return 0


def _f(v, sign=False):
    if v is None:
        return "--"
    return f"{v:+.3f}" if sign else f"{v:.3f}"


if __name__ == "__main__":
    sys.exit(main())
